### ISSUE TITLE
ProcedureResultSet is not properly exposed as a child of a Procedure using getChildren()

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#69]
Method is missing a check on existance of a Result Set and adding it to the child list.

Note also that the getResultSet() will lazily create the result set if asked for, so we'll need to re-think that behavior??

    public KomodoObject[] getChildren( final UnitOfWork uow ) throws KException {
        return getParameters(uow);
    }

**Comment by elvisisking** [comment]
I made the assumption procedures would always have a result set. Thinking about it more, that is probably not true. Right? What if I add a boolean parameter to `getResultSet()` to indicate if the result set should be created or not? The result set has a predefined name so that cannot be set. Also will changed `getChildren()` to include the result set.

**Comment by blafond** [comment]
See:  https://developer.jboss.org/wiki/ProcedureAndFunctionDefinition  I created this to capture procedure rules/structure and Hawkins added his 2 cents worth.

**Comment by blafond** [comment]
https://github.com/Teiid-Designer/komodo/pull/76
https://github.com/Teiid-Designer/komodo/pull/75
https://github.com/Teiid-Designer/komodo/pull/74
https://github.com/Teiid-Designer/komodo/pull/73
